version: "2"
services:
  grupviz-app:
    build: ./app
    ports:
    - "4000:4000"
    volumes:
     - ./app:/usr/src/app
    links:
      - mongo
    restart: always
  mongo:
    image: mongo
    container_name: mongo
    restart: always