version: "2"
services:
  grupviz-app:
    build: ./app
    ports:
    - "3000:8080"
    volumes:
     - ./app:/usr/src/app
    link:
      - mongo
    restart: always
  mongo:
    image: mongo
    restart: always